<a href="https://colab.research.google.com/github/Mysterio-maker/STUDY-OF-PANDAS-IN-PYTHON/blob/main/EXPERIMENT_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Experiment 9

## Title- Study of pandas

## Amey Waghmare
## 25070123009
## A1

In [ ]:
# PANDA - USED FOR STRUCTURED DATA
          DATA CLEANING

In [ ]:
import pandas as pd

s= pd.Series([7,8,10,18,45])
s

0     7
1     8
2    10
3    18
4    45
dtype: int64

In [ ]:
# CREATE DATA FRAME

data={
    "Name":["A","B","C","D"],
    "Marks":[85,90,95,100]
}
df=pd.DataFrame(data)
df

  Name  Marks
0    A     85
1    B     90
2    C     95
3    D    100

In [ ]:
df.head()

  Name  Marks
0    A     85
1    B     90
2    C     95
3    D    100

In [ ]:
df.tail()

  Name  Marks
0    A     85
1    B     90
2    C     95
3    D    100

In [ ]:
# Find structure of DataFrame
df.shape

(4, 2)

In [ ]:
df.ndim

2

In [ ]:
df.size

8

In [ ]:
# Display Column Names
df.columns

Index(['Name', 'Marks'], dtype='object')

In [ ]:
df.dtypes

Name     object
Marks     int64
dtype: object

In [ ]:
# Access individual column

df["Name"]

0    A
1    B
2    C
3    D
Name: Name, dtype: object

In [ ]:
# Access specific row

df.loc[1]

Name      B
Marks    90
Name: 1, dtype: object

In [ ]:
# Adding a column

df["Grade"]=["First Class","Distinction","Second Class","Fail"]
df

  Name  Marks         Grade
0    A     88   First Class
1    B     90   Distinction
2    C     95  Second Class
3    D    100          Fail

In [ ]:
# Update Data in data frame

df.loc[0,"Marks"]= 88
df

  Name  Marks
0    A     88
1    B     90
2    C     95
3    D    100

In [ ]:
df.drop("Grade", axis=1, inplace=True)
df

  Name  Marks
0    A     88
1    B     90
2    C     95
3    D    100

In [ ]:
# perfrom basic statistical operations

df["Marks"].mean()

np.float64(93.25)

In [ ]:
df["Marks"].max()

100

In [ ]:
df["Marks"].min()

88

In [ ]:
# Apply Conditioning

df[df["Marks"] > 90]

  Name  Marks
2    C     95
3    D    100